name: Server Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build ./server --file ./server/Dockerfile --tag docker.pkg.github.com/carlosdp/party-from-home/lockdown-server:${{ github.sha }}
      - name: Tag latest
        run: docker tag docker.pkg.github.com/carlosdp/party-from-home/lockdown-server:${{ github.sha }} docker.pkg.github.com/carlosdp/party-from-home/lockdown-server:latest
      - name: Push Image
        run: docker login docker.pkg.github.com -u ${{ secrets.GITHUB_USERNAME }} -p ${{ secrets.GITHUB_TOKEN }} && docker push docker.pkg.github.com/carlosdp/party-from-home/lockdown-server
      - name: curl
        uses: wei/curl@master
        with:
          args: >
            -u "keel:${{ secrets.KEEL_PASSWORD }}" -d '{\"name\": \"docker.pkg.github.com/carlosdp/party-from-home/lockdown-server\", \"tag\": \"latest\"}' https://keel.carlos-dp.com/v1/webhooks/native
